server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #注册中心地址
  instance:
    instance-id:  gateway-9527 #eureka中微服务实例别名
    prefer-ip-address: true #显示微服务实例的IP

info:
  app.name: xiang-microcloud
  company.name: www.xiang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#zuul 路由访问规则
zuul:
  prefix: /xiang  #前缀
  ignored-services: "*" #屏蔽所有真实微服务的名字 ，只能用下面配置的别名访问
  routes: #路由   microservicecloud-dept  mydept映射
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**